// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR0jY4Im-h4LcBVVB85N_iBUUq7O5JJEE',
    appId: '1:150941865624:web:a5b9a087c6863a5914e2ed',
    messagingSenderId: '150941865624',
    projectId: 'chaldim-tourist',
    authDomain: 'chaldim-tourist.firebaseapp.com',
    storageBucket: 'chaldim-tourist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApAJo-Vt00RGk8B4kg6rlvfoer8hp6_oY',
    appId: '1:150941865624:android:58ca6609b4a3f77414e2ed',
    messagingSenderId: '150941865624',
    projectId: 'chaldim-tourist',
    storageBucket: 'chaldim-tourist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPKLcic0h16Y0z_E_BGe_5_H4t4-g1UA',
    appId: '1:150941865624:ios:6ffa8e7374cbf35f14e2ed',
    messagingSenderId: '150941865624',
    projectId: 'chaldim-tourist',
    storageBucket: 'chaldim-tourist.appspot.com',
    iosBundleId: 'com.example.chaldimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoPKLcic0h16Y0z_E_BGe_5_H4t4-g1UA',
    appId: '1:150941865624:ios:6ffa8e7374cbf35f14e2ed',
    messagingSenderId: '150941865624',
    projectId: 'chaldim-tourist',
    storageBucket: 'chaldim-tourist.appspot.com',
    iosBundleId: 'com.example.chaldimApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR0jY4Im-h4LcBVVB85N_iBUUq7O5JJEE',
    appId: '1:150941865624:web:d8bec21c41dd4eac14e2ed',
    messagingSenderId: '150941865624',
    projectId: 'chaldim-tourist',
    authDomain: 'chaldim-tourist.firebaseapp.com',
    storageBucket: 'chaldim-tourist.appspot.com',
  );

}